# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Markdown2pdf < Formula
  desc "Convert Markdown with code blocks, diagrams, and images to PDF"
  homepage "https://github.com/dlouwers/markdown2pdf"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dlouwers/markdown2pdf/releases/download/v1.2.0/markdown2pdf_1.2.0_darwin_amd64.tar.gz"
      sha256 "fc9aad466979cfe7498932c6b8c253f2034f255325ba99aca9446bc719b6c12f"

      define_method(:install) do
        bin.install "markdown2pdf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dlouwers/markdown2pdf/releases/download/v1.2.0/markdown2pdf_1.2.0_darwin_arm64.tar.gz"
      sha256 "687aa5c79d305e635ffd8becf509b08b77aeaa78eaca635a58f202227bf3ff09"

      define_method(:install) do
        bin.install "markdown2pdf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/markdown2pdf/releases/download/v1.2.0/markdown2pdf_1.2.0_linux_amd64.tar.gz"
      sha256 "9a0033d0d6a67a345e4e764c0094678ad324f09401a18cdcaa6663adabfa0279"
      define_method(:install) do
        bin.install "markdown2pdf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dlouwers/markdown2pdf/releases/download/v1.2.0/markdown2pdf_1.2.0_linux_arm64.tar.gz"
      sha256 "acf8bcfe0d744f101204c8cd19c4561f7c2c578e96202ea64be1de8a6a170ad4"
      define_method(:install) do
        bin.install "markdown2pdf"
      end
    end
  end

  test do
    system "#{bin}/markdown2pdf", "--version"
  end
end
